### ISSUE TITLE
HEVC file sizes

### ISSUE THREAD

**Issue by geddy76** [donmelton/more-video-transcoding#10]
Should I really be getting file sizes as low as I am? I’m using HEVC-transcode without any options/flags on 4k HDR rips. The Abyss was 3.5 gigs. Blade Runner 2049 was 1.5. Resulting file is still 4k and HDR. Is HEVC that good??

**Comment by lisamelton** [comment]
@geddy76 It would be much more helpful to know the output video bitrates of your transcoded files. Sizes don't mean much. But those do sound about right.

HEVC, specifically the produced by the `x265` encoder used in the `hevc-transcode.rb` script, is very efficient and high quality. But please realize you're probably seeing very low bitrates because the film content you mention is low complexity and/or flat. It's not gonna take a lot of bits to render those. Try something more challenging like "Saving Private Ryan" to test the encoder.

Does this answer your question?

**Comment by geddy76** [comment]
The Abyss is 2752 kbps and Blade Runner 2049 is 1219 kbps. But your explanation makes total sense. I’m just amazed that these are smaller than DVD files. 

I don’t have Saving Private Ryan (sacrilege), but I have Dunkirk and 1917. I figure those might be similar. 

Appreciate the response. Sorry for using this like a forum.

**Comment by lisamelton** [comment]
@geddy76 No apologies necessary! It's OK to open an issue to ask a question. And that was a good question, too! 💖
