### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by gadgetgeek27** [donmelton/more-video-transcoding#16]
Good day @lisamelton 

I'm a long time user of your transcoding tools. Thank you for all of your efforts! The change to Ruby and specifically no longer using ruby gems has left me seeking assistance.

How do I copy `other-transcode.rb` to a directory listed in the `$PATH` environment variable on macOS? I don't understand how to achieve this. I apologize if this is remedial. 

I have ruby installed and followed all of your instructions. I have also ensured that I uninstalled other video transcoding with "gem uninstall other_video_transcoding".

Any assistance you or others can provide, would we greatly appreciated!

Thanks again.

**Comment by lisamelton** [comment]
@gadgetgeek27 You're very welcome!

Since you want to install my `other-transcode.rb` script, I think you've opened this issue on the wrong project. But I'll answer your question anyway.

Often the directories listed in the macOS `$PATH` environment variable may not be writable by anyone other than the superuser. So, you may need to preface your `cp` command with `sudo` to act as the superuser. Typically, you want to install a script into the local executable directory. Here's how I would recommend doing that:

```
sudo cp other-transcode.rb /usr/local/bin/
```

Does that help?

**Comment by gadgetgeek27** [comment]
@lisamelton Yes it helped. Thanks so kindly. It works perfectly now. 
I REALLY appreciate your time and efforts. 

Enjoy your weekend!

**Comment by lisamelton** [comment]
@gadgetgeek27 Great! I'm so glad. 💖
